const standardLocationDurations: Record<string, number> = {
    'pico-do-arieiro': 180,
    'fanal-forest': 120,
    'praia-do-porto-do-seixal': 120,
    'machico-beach': 150,
    'faja-dos-padres': 240,
    'calheta-beach': 180,
    'prainha-do-canical': 180,
    'porto-moniz-natural-pools': 150,
    'ribeira-da-janela': 30,
    funchal: 90,
    'mercado-dos-lavradores': 30,
    'cristo-rei': 45,
    'pico-do-facho': 30,
    'cabo-girao-skywalk': 30,
    'anjos-waterfall': 30,
    'miradouro-do-guindaste': 30,
    'levada-nova-levada-do-moinho': 150,
    'monte-palace-tropical-garden': 120,
    'santana-typical-houses': 15,
    'ponta-de-sao-lourenco': 180,
    'miradouro-sao-cristovao': 30,
    'continente-modelo-machico': 45,
    'continente-modelo-canico-shopping': 45,
    'continente-modelo-agua-de-pena': 45,
    'continente-modelo-camacha': 45,
    'continente-modelo-cancela': 45,
    'continente-modelo-viveiros': 45,
    'continente-modelo-seminario': 45,
    'continente-modelo-santo-antonio': 45,
    'continente-modelo-madeira-shopping': 45,
    'continente-modelo-santana': 45,
    'continente-modelo-camara-de-lobos': 45,
    'continente-modelo-monumental': 45,
    'continente-modelo-sao-martinho': 45,
    'continente-modelo-ribeira-brava': 45,
    'continente-modelo-ribeira-brava-centro': 45,
    'continente-modelo-estreito-de-camara-de-lobos': 45,
    'pingo-doce-machico': 45,
    'pingo-doce-camara-de-lobos': 45,
    'pingo-doce-plaza-madeira': 45,
    'pingo-doce-anadia': 45,
    'pingo-doce-funchal': 45,
    'pingo-doce-ribeira-brava': 45,
    'pingo-doce-santo-antonio': 45,
    'pingo-doce-brito-camara': 45,
    'pingo-doce-penteada': 45,
    'pingo-doce-cancela': 45,
    'pingo-doce-monumental': 45,
    'pingo-doce-calheta': 45,
};
export function plannerStopDuration(location: { slug: string; tags: string[] }) {
  return location.tags.includes("Airport") ? 15 : standardLocationDurations[location.slug] ?? 90;
}
